### ISSUE TITLE
Run a test on the container before publish

### ISSUE THREAD

**Issue by philchristensen** [esatterwhite/semantic-release-docker#20]
I'd like to be able to execute a shell command after the Docker image is built, but before it's pushed to the repo. A failure in this command would terminate the release pipeline.

I tried to do this with a custom `exec` pipeline stage, but there's no way in that stage to know the name of the recently built image, because the tag used is randomly generated with `crypto.randomBytes(10).toString('hex')`. Using `latest` just makes docker pull down the previously built image.

Can you think of any other way that I might be able to run a command on the recently built container before push?

**Comment by esatterwhite** [comment]
Hey @philchristensen.
I like this idea. I have wanted to be able to run something during the verify step to make sure the build actually work before going to publish.

Its pretty common to want to do a dry run on a branch before merging, but you don't quite know that the docker build will actually work. And the verify step is the only way to do that.

It could work during the publish step, but I think in the common case that might be too late.


Are you thinking that you would build the image and rather than publishing, it run some `docke exec` command?
if so, I think that is pretty doable. But My thought is to make that happed during the `verify` stage rather than publish

**Comment by philchristensen** [comment]
Yeah, my thoughts exactly. I’ll try to take a whack at it.
