### ISSUE TITLE
Single base image with multiple versions

### ISSUE THREAD

**Issue by iamjohnnym** [esatterwhite/semantic-release-docker#24]
Is it possible to leverage this project to build multiple versions from a single base image?

Let's say I have a singular project for generating a semver'd python image.  My Dockerfile has a `FROM python:$VERSION`.  I'd like to generate a semver'd image for the following versions:

- 3.8.x
- 3.9.x
- 3.10.x

My end result would be a singular project with various base images of different python versions.

python-3.8.0:latest, python-3.8.0:1-latest, python-3.8.0:1.0.0
python-3.9.0:latest, python-3.9.0:1-latest, python-3.9.0:1.0.0
python-3.10.0:latest, python-3.10.0:1-latest, python-3.10.0:1.0.0

**Comment by esatterwhite** [comment]
@iamjohnnym I think this might be going against how semantic release wants to work in general. Currently this project isn't set up for that (monorepos) currently. semantic release assumes a 1:1 mapping of repo to release / artifact. It'd be possible to accept arrays of configuration or you can also define the plugin multiple times in your release config each for a specific version, but i'm not sure that will really work out too well either.

What I might suggest is using [multi-semantic-release](https://www.npmjs.com/package/multi-semantic-release) for this purpose. 

I have used this with pretty good success in combination with [pnpm](https://pnpm.js.org) for inter dependent projects in a single repo

[Here](https://github.com/esatterwhite/semantic-release-tools) is a project that uses this setup for multiple npm packages rather than docker images, but the principle still applies.  The release config is defined in the root package.json and that is applied to all the projects in `packages`

pnpm is setup to track [workspace packages](https://github.com/esatterwhite/semantic-release-tools/blob/main/.npmrc#L3). So when a change is made to `release-config-core` which the other two projects depend on,

**Comment by iamjohnnym** [comment]
Awesome.  Thanks for the suggestion, I'll check that out.
